.TH CLFUN 1
.SH NAME
clfun \- perform 3D interactive Quartet Tree Reconstruction on a distance matrix to produce a binary tree
.SH SYNOPSIS
.B clfun
.I distmatrix.clb
.SH DESCRIPTION
.B clfun
tries to find an optimal tree to represent an input distance matrix \fBmatrix.txt\fR.
It uses the Quartet Tree Reconstruction method.  The program starts with a
random tree, and continues to try small modifications to improve the tree
score.  Eventually, the tree will stop easily improving.  The algorithm will
then write the best tree it found to \fBtreefile.dot\fR.  This is a
\fB.dot\fR-format file, which means that it can be used with the \fBgraphviz\fR
package tools such as \fBdot (1)\fR or \fBneato (1)\fR. If the distance matrix
is unlabelled, the external nodes are labelled with K-i, i starting at 0.

.PP
Input files for this program can be created by \fBncd (1)\fR.
.PP
For more information on the details of this algorithm, please see
\fIAlgorithmic Clustering of Music\fR by \fBCilibrasi, Vitanyi,\fR and \fBde Wolf\fR at \fBhttp://www.arxiv.org/abs/cs.SD/0303025\fR
.SH OPTIONS

There are no options for clfun yet.

.SH FILES
.I $HOME/.complearn/config.yml
.RS
per-user configuration file, overrides systemwide default; see
.BR complearn (5)
for further details.
.SH ENVIRONMENT
none
.SH DIAGNOSTICS
If any of the files cannot be read, an error will be printed and the program exits with a nonzero exit code.
.SH "SEE ALSO"
.BR complearn (5),
.BR ncd (1),
.BR maketree (1)
