/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __COMPLEARN_RCBZIP_PRIVATE_H__
#define __COMPLEARN_RCBZIP_PRIVATE_H__

#include "complearn-rcbzip.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
