Document: complearn-gui
Title: Debian complearn-gui Manual
Author: <insert document author here>
Abstract: This manual describes what complearn-gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/complearn-gui/complearn-gui.sgml.gz

Format: postscript
Files: /usr/share/doc/complearn-gui/complearn-gui.ps.gz

Format: text
Files: /usr/share/doc/complearn-gui/complearn-gui.text.gz

Format: HTML
Index: /usr/share/doc/complearn-gui/html/index.html
Files: /usr/share/doc/complearn-gui/html/*.html

  
