Document: libcsoap
Title: Debian libcsoap Manual
Author: <insert document author here>
Abstract: This manual describes what libcsoap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcsoap/libcsoap.sgml.gz

Format: postscript
Files: /usr/share/doc/libcsoap/libcsoap.ps.gz

Format: text
Files: /usr/share/doc/libcsoap/libcsoap.text.gz

Format: HTML
Index: /usr/share/doc/libcsoap/html/index.html
Files: /usr/share/doc/libcsoap/html/*.html

  
