Document: libcomplearn
Title: Debian libcomplearn Manual
Author: <insert document author here>
Abstract: This manual describes what libcomplearn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcomplearn/libcomplearn.sgml.gz

Format: postscript
Files: /usr/share/doc/libcomplearn/libcomplearn.ps.gz

Format: text
Files: /usr/share/doc/libcomplearn/libcomplearn.text.gz

Format: HTML
Index: /usr/share/doc/libcomplearn/html/index.html
Files: /usr/share/doc/libcomplearn/html/*.html

  
