#!/home/webuser/bin/ruby

require 'fileutils'

scriptdir = File.dirname(__FILE__)
filename = scriptdir + "/../configure.ac"
newname = scriptdir + "/../configure.ac.new"
backup = scriptdir + "/../configure.ac.bak"

src = IO.readlines(filename)

File.rename(filename, backup)

output = File.new(filename,"w")

src.each { |line|
  if line =~ /AM_INIT_AUTOMAKE\(libcomplearn[^,]*, (\d+).(\d+).(\d+)/
    major, minor, micro = $1.to_i, $2.to_i, $3.to_i
    line.gsub!(/(\d+).(\d+).(\d+)/,major.to_s + '.' + minor.to_s + '.' + (micro+1).to_s)
    puts "Bumping version number to #{major}.#{minor}.#{micro+1}..."
  end
  output.write(line)
}

output.close
puts "Generating new distribution..."

# running reconf script
`./#{scriptdir}/reconf.zsh`

# make distribution
`cd #{scriptdir}/.. ; make dist`

puts "Packaging complete"
