#!/bin/zsh

DEST=/home/svn/public_html/complearn/downloads
CMDDIR=`dirname $0`

if test `id -u` '!=' 0 ; then
	echo 'You must be root to run this script.'
	exit 1
fi
while true ; do
  SRC=$1
  test "x$SRC" = "x" && exit 0
  shift
  $CMDDIR/cp2svn $SRC $DEST
done
