#ifndef __DMLABELS_H
#define __DMLABELS_H

/*! \file labelmaker.h */

/** \brief Serializes a StringStack of distance matrix labels into a DataBlock
 *
 *  dumpDMLabels() returns to DataBlock which then can be written to
 *  a file using the function datablockWriteToFile().  This resulting DataBlock
 *  is also appropriate when using the function package_DataBlocks().
 *
 *  To convert the resulting DataBlock back into an StringStack, use the
 *  loadDMLabels() function.
 *  \param ss pointer to StringStack
 *  \return serialized DataBlock
 */
struct DataBlock dumpDMLabels(struct StringStack *ss);

/** \brief Converts DataBlock created by dumpDMLabels() back into a StringStack
 *
 *  loadDMLabels() will take as an argument a DataBlock, which was
 *  most likely created by the dumpDMLabels() function, and convert the
 *  DataBlock into a StringStack. A pointer to the StringStack is returned.
 *
 *  An option to loadDMLabels() is the fmustbe flag, which, if set to 1, forces
 *  the function to exit if the check for the special DMLabels tag created by
 *  dumpDMLabels() fails.  If the tag is not found, an error message is printed
 *  to stdout. Set fmustbe to 0 to return NULL instead.
 *
 *  \param db DataBlock
 *  \param fmustbe 1 if the DataBlock must contain the identifying DMLabels
 *  flag; 0 if not
 *  \return pointer to new StringStack
 */
struct StringStack *loadDMLabels(struct DataBlock db, int fmustbe);

/** \brief Returns StringStack of distance matrix labels from CompLearn binary
 *
 *  get_labels_from_clb() is a high level function which reads a CompLearn
 *  binary(clb) file, generated by the ncd -b command and returns a StringStack
 *  of labels for the distance matrix saved in the clb file.
 *  \param fname path to CompLearn binary file
 *  \return StringStack of distance matrix labels
 */
struct StringStack *get_labels_from_clb(char *fname);

/** \brief Returns StringStack of distance matrix labels from a ASCII text file
 *
 *  get_labels_from_txt() is a high level function which reads a text file,
 *  formatted in the same way as output from the ncd command, and returns a
 *  StringStack of labels for the distance matrix.
 *  \param fname path to text file
 *  \return StringStack of distance matrix labels
 */
struct StringStack *get_labels_from_txt(char *fname);

/** \brief Dumps a StringStack of commands into a serialized DataBlock
 *
 *  Used to capture commands when using the ncd and maketree commands.
 *  \param ss pointer to StringStack of commands
 *  \return DataBlock
 */
struct DataBlock dumpCommands(struct StringStack *ss);

/** \brief Returns StringStack of commands from a CompLearn binary file
 *
 *  get_clcmds() is a high level function which reads a CompLearn binary (clb)
 *  file, generated from the ncd -b command, and returns a StringStack of
 *  commands.
 *  \param fname path CompLearn binary file
 *  \return StringStack of commands
 */
struct StringStack *get_clcmds_from_clb(char *fname);

#endif
